import{S as f,i as u}from"./assets/vendor-5b791d57.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const r of o.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&i(r)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const a=document.querySelector(".search-form"),l=document.querySelector(".gallery"),c=new f(".gallery a");console.log(c);l.innerHTML="";a.addEventListener("submit",g);function g(s){s.preventDefault(),console.log(a.elements.searchText.value),fetch(`https://pixabay.com/api/?key=40858721-2ab2962236a746e97c71283b6&q=${a.elements.searchText.value}&image_type=photo&orientation=horizontal&safesearch=true,`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()}).then(t=>{t.hits.length===0?u.show({message:"Sorry, there are no images matching your search query. Please try again!",close:!1,backgroundColor:"red",messageColor:"white",messageSize:20,timeout:0,position:"topRight"}):(l.innerHTML=h(t.hits),console.log(l),c.refresh(),console.log(c))}).catch(t=>{u.show({title:"Error",message:"Something goes wrong, please try reload page.",close:!1,backgroundColor:"red",messageColor:"white",messageSize:20,timeout:0,position:"topRight"})})}function h(s){return s.map(({webformatURL:t,tags:n,likes:i,views:e,comments:o,downloads:r,largeImageURL:m})=>`<div class="photo-card">
        <a href="${m}">
      <img class="item-image" src="${t}" alt="${n}" width="400" height="240" loading="lazy" />
      </a>
      <div class="info"><p class="info-item"><b>Likes</b><br>${i}</p>
      <p class="info-item"><b>Views</b><br>${e}</p>
      <p class="info-item"><b>Comments</b><br>${o}</p>
      <p class="info-item"><b>Downloads</b><br>${r}</p></div></div>`).join("")}
//# sourceMappingURL=commonHelpers.js.map
